music.setVolume(90)
music.setTempo(58)
music.playTone(698, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(698, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(698, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(698, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Eighth))
music.playTone(659, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Eighth))
music.playTone(523, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Half))
